id: P010628
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC310
  title: 'རྒྱའི་ཡིག་ཚང་དུ་འཁོད་པའི་བོད་དང་འབྲེལ་བའི་ལོ་རྒྱུས། （༡）སྲིད་སྐྱོང་མེ་ལོང་ལས་བྱུང་བའི་བོད་བཙན་པོའི་དུས་ཀྱི་ལོ་རྒྱུས། '
  author: ''
  volumes: {}
