id: P010628
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC310
  title: 'རྒྱའི་ཡིག་ཚང་དུ་འཁོད་པའི་བོད་དང་འབྲེལ་བའི་ལོ་རྒྱུས། （༡）སྲིད་སྐྱོང་མེ་ལོང་ལས་བྱུང་བའི་བོད་བཙན་པོའི་དུས་ཀྱི་ལོ་རྒྱུས། '
  author: ''
  volumes:
    41968163d9b94bf3992bf8ce54dde66a:
      image_group_id: I4PD4207
      title: ''
      volume_number: 1
      total_pages: 396
      base_file: v001.txt
